name: docker

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/docker.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: determine_tag
        name: Determine tag version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "::set-output name=tag::$(echo ${{ github.ref }} | sed -e 's|refs/tags/||' | sed -e 's/^v//')"
      - name: Build Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: madscience/action-node/action-node
          always_pull: true
          tags: ${{ steps.determine_tag.outputs.tag }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
    outputs:
      tag: ${{ steps.determine_tag.outputs.tag }}

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]

    runs-on: ubuntu-latest
    steps:
      - name: Publish release tags to GitHub Package Registry
        uses: flownative/action-docker-publish-semver@v1.2.0
        with:
          tag_ref: ${{ needs.build.outputs.tag }}
          tag_latest: yes
          #tag_custom: 'some-custom-tag'
          source_image_name: docker.pkg.github.com/madscience/action-node/action-node
          source_registry_username: ${{ github.actor }}
          source_registry_password: ${{ secrets.GITHUB_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/
          target_image_name: madsci/action-node
          target_registry_username: egornz
          target_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          target_registry_endpoint: https://index.docker.io/v2/
